Enhancements for EP brakes
openrails/openrails pull request #1015
Opened 2024-12-19 09:43 UTC by cesarBLG

https://trello.com/c/UJK7mUB3/602-include-new-ep-brake-components

2025-01-03 03:16 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/MSTSBrakeSystem.cs
> +            HandBrakePresent = equipment.Contains("handbrake");
This function and other places using the "equipment" variable are causing an error on a "wagon" in my collection with **no BrakeEquipmentType** defined (actually an EOTD treated as a wagon). This EOTD was made before the dedicated EOTD feature was added, so to get the most accurate EOTD given the basic wagon system, I configured it as a wagon with just a brake pipe and **nothing else** (no triple valve, no brake cylinder, no handbrake, as an EOTD really only has a brake pipe and nothing else ORTS might be interested in).

While this worked previously, the changes in this PR effectively require that a wagon has some sort of brake equipment, as equipment being null causes this and other operations to fail. The actual simulation seems to work fine even if BrakeEquipment is empty, so I'd recommend adding an `equipment != null` check anywhere that currently assumes equipment isn't null.

2025-01-03 03:18 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/AirSinglePipe.cs
> +            if (equipment.Contains("distributor") || equipment.Contains("graduated_release_triple_valve")) BrakeValve = BrakeValveType.Distributor;
This function is another place that assumes equipment is not null even though it might be null.

2025-01-03 07:58 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/MSTSBrakeSystem.cs
> +            HandBrakePresent = equipment.Contains("handbrake");
I simply initialized the equipment as an empty list, I think that makes more sense and it is also simpler.

2025-01-03 23:11 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/MSTSBrakeSystem.cs
> +            HandBrakePresent = equipment.Contains("handbrake");
Looks like that worked, the EOTD is loading again.

2025-02-11 03:55 UTC, SteelFill requested changes
All the features seem to work properly and the refactor has helped to clean things up without any problems reported recently. The additions here look like they'll be very useful for many EP systems, I especially like seeing single pipe EP as that finally allows for plausible simulation of ECP braking (last thing ECP needs is some way for an EP brake signal to demand emergency brake cylinder pressure-the solenoid valve is not appropriate for single pipe systems).

Merge conflict still needs to be solved, and I was left unsatisfied trying to implement a train brake controller with mixed EP and westinghouse braking due to limitations in the default brake controller script.

2025-02-11 08:18 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
Could you specify which is the specific behaviour that you wish to achieve? I don't really understand it. If BrakeLine4 == -2, the holding valve is activated, which prevents the brakes from being released. This allows implementing controllers with Release-EP-Air notches.

2025-02-13 03:37 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
I was trying to do a controller with release, EP only, then graduated self lapping, BUT using `ORTSEPBrakeInhibitsTripleValve ( 1 )` (this works basically how I'd expect when the triple valve isn't inhibited, but that's not the system I was trying to create). I fired up the debugger, and the reason the brake cylinder pressure goes to 0 is the new [line 135 of EPBrakeSystem.cs](https://github.com/cesarBLG/openrails/blob/3ee3108b3366e9f0f6a11600ac09c79d75a50cf7/Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs#L135). That sets the holding valve to release _regardless of the EP wire value_. I guess that guarentees any pneumatic applications to leak off, but also leaks off EP applications too when the EP wire is -2 ([line 130](https://github.com/cesarBLG/openrails/blob/3ee3108b3366e9f0f6a11600ac09c79d75a50cf7/Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs#L130) is never reached so the demanded pressure remains set to 0).

Also, a consequence of this is that a break in two does not cause any brake application when the triple valve is inhibited. Triple valve state of emergency should bypass the isolation valve.

2025-02-13 09:01 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
If the EP brakes are inhibiting the triple valve, the Holding Valve should be always set to release, since essentially the triple valve is isolated from the brakes. The holding valve is attached to the Release port of the triple valve, and the isolation valve is attached to the Brake Cylinder port of the triple valve. If the isolation valve is activated, what happens to the holding valve is irrelevant for braking. When EPBrakeActiveInhibitsTripleValve is set, EP brake release happens through a different port than triple valve release. To achieve what you want, I will prevent EP brakes from being released if the holding wire is active.

> Also, a consequence of this is that a break in two does not cause any brake application when the triple valve is inhibited. Triple valve state of emergency should bypass the isolation valve.

Is that the standard behavior in America? In Europe, there is an electrical brake continuity wire (which I haven't implemented yet). If the train breaks in two, the wire is broken and emergency brakes are applied. This wire is present also in MU trains without EP brakes.

2025-02-16 22:31 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
The standards for stuff here in America do require an emergency application when brake pipe integrity is lost, and there even needs to be an entirely pneumatic system to handle emergency application and propagation in case the electronics are dead (though that requirement is more relevant for equipment without a traditional control valve). The assumption still is that the brake pipe should be used as a fail safe.

2025-02-17 09:55 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
Of course in Europe it is also mandatory that brakes are applied in case of train splitting. However, the integrity check is typically electrical in MUs: if train splits, the continuity wire is de-energized and the emergency solenoid valves return to the stable emergency position, applying full brakes. With this variant of EP braking (which is not the interoperable UIC EP braking), the brake pipe is used as a fall-back, but only if EP braking is inactive. I can think of two variants of this system:
- While EP braking is active, the BP pressure is always ignored (it can even be kept at 0bar), brake application and release is fully handled by the EP valves.
- While EP braking is active, BP pressure is also varied. If the demand from EP brakes matches the one from the air brakes (with some tolerance), BP pressure is ignored.

I think these two variants can be simulated by setting ORTSEPBrakeInhibitsTripleValve to 1 or 0 respectively. Thus, I don't really understand your use case, where you want the EP brake to inhibit the triple valve braking, but still have the BP as a fall-back. That's what you get with ORTSEPBrakeInhibitsTripleValve ( 0 ), or do you want to achieve something different?

2025-02-18 04:09 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
Not inhibiting the triple valves works for emergency sure but causes all manner of unintended effects during a regular application. In ECP braking, the brake pipe is just the supply pipe so naturally varies a bit as air is moved around and reservoirs recharge. If the triple valves are still listening to the brake pipe while ECP things are happening, you get quick service and quick release action in response to "brake applications" occurring, when in reality the brake pipe pressure is dropping to refill reservoirs. That triple valve action is unrealistic, causes additional unusual waves in brake pipe pressure, and just wastes air.

2025-02-18 08:24 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
Ah, now I understand what's the system that you're implementing, thanks. There are two different solutions that come up to my mind:
- If the BC pressure that would be demanded by the BP is higher than the BC pressure demanded by the ECP system, then the triple valve is connected to the brake cylinders. This could be achieved by a new parameter such as EPBrakeTripleValveInhibitionThreshold( pressureBar ). I know at least one MU which works precisely like this.
- If EP brakes are operational, the triple valve is inhibited unless in emergency position.

Do you know which variant is the one used as a fallback for ECP braking? I don't see anything at http://www.railway-technical.com/trains/rolling-stock-index-l/train-equipment/brakes/electro-pneumatic-brakes-d.html . They only mention that if no ECP signal is received after some time, an emergency braking is triggered.

2025-02-20 01:29 UTC, SteelFill commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
The typical approach, which seems to be what the specification intends, is that the service portion of the triple valve is disabled while ECP is functional but the emergency portion is not, hence you should still get emergency detection and emergency vent valves even in ECP mode. The intent is that the electronic system should still handle emergency brake cylinder pressure (especially if the pressure required is lower than normal due to a light load) but that it won't matter if it can't (the OR EP system sure won't) because the "dumb" system will also have intervened.

But even if the triple valve is allowed to kick in, that doesn't change that OR's EP system can only do service applications, can't use air from the emergency res, and can't ignore the train brake setting to apply brakes for a different reason, so ECP still isn't going to turn out great, not the best system to attempt simulating.

2025-03-15 13:14 UTC, cesarBLG commented on Source/Orts.Simulation/Simulation/RollingStocks/SubSystems/Brakes/MSTS/EPBrakeSystem.cs
>              if (lead == null || !(lead.BrakeSystem is EPBrakeSystem) || Car.Train.BrakeLine4 == -1)
Okay, I disabled the inhibition valve when an emergency is detected. The electrical continuity wire is left for a further PR, as that needs interaction with the TCS.

2025-03-30 20:36 UTC, SteelFill approved these changes
The new EP single pipe system is now working good enough for my purposes, and the other additional features work as described. Refactoring looks good to, that helps keep things organized. You are good to merge and free up all these files for other changes.

2025-03-31 07:15 UTC, cesarBLG commented
Thanks, Philip!

2025-03-31 07:15 UTC, merged