Adds index of parameters to Manual
openrails/openrails pull request #275
Opened 2020-09-10 19:08 UTC by cjakeman

Entries for parameters are added to the index section at the end of the manual.

So far chapters 1-8 included (including Open Rails Physics).

See forum thread http://www.elvastower.com/forums/index.php?/topic/34208-missing-from-the-manual/
and Trello card https://trello.com/c/RAqEtB7j/224-document-engine-and-wagon-parameters

2020-09-11 21:05 UTC, YoRyan approved these changes

2020-09-15 17:39 UTC, YoRyan commented
Hi Chris,

I see that you're still pushing commits. In that case, I'll convert this PR to a draft. Let me know when it's ready to be approved.

2020-09-17 19:16 UTC, cjakeman commented
> Hi Chris,
> 
> I see that you're still pushing commits. In that case, I'll convert this PR to a draft. Let me know when it's ready to be approved.

Thanks, Ryan. Will do.

2020-09-23 08:01 UTC, YoRyan requested changes
Excellent and necessary work, Chris. Just have a small typo to look at and then I'll approve.

2020-09-26 21:07 UTC, cjakeman commented on Source/Documentation/Manual/cabs.rst
> +v
Sorted. Thanks.

2020-09-28 08:30 UTC, YoRyan approved these changes
Okay, this looks good!

2020-09-28 18:27 UTC, merged