Some strings should not be extracted for translation
openrails/openrails pull request #514
Opened 2021-10-07 14:25 UTC by mbm-OR

Some strings are used as internal keywords and should not be extracted to the *.pot file for translation.
Fix for https://bugs.launchpad.net/or/+bug/1946373.

2021-10-08 02:00 UTC, Sharpe49 requested changes
You should probably update the POT files to check if some keywords are still translated and then add the updated POT files to this pull request.

2021-10-09 13:15 UTC, mbm-OR commented
> 
> 
> You should probably update the POT files to check if some keywords are still translated and then add the updated POT files to this pull request.

Currently, no keywords pointed by this PR, have been translated in any "* .PO" files.
Once updated with update.bat, these keywords appear in the POT file, so if they don't need to be translated, they should not appear in the POT file either.
That is the reason for this PR, suggested by Weter, [here.](http://www.elvastower.com/forums/index.php?/topic/26556-translations-unclear-strings-other-problems/page__view__findpost__p__276547)

2021-10-10 04:50 UTC, Sharpe49 commented
What I mean is that the previously translated keywords are still in the POT file. For example : https://github.com/openrails/openrails/blob/fab59f576535f027a2ccac044b9de4cbd4d74900/Source/Locales/RunActivity/RunActivity.pot#L1912
You need to remove those keywords from the POT file.

2021-10-12 20:12 UTC, Sharpe49 approved these changes

2021-10-12 20:12 UTC, merged