Fix VRAM usage
openrails/openrails pull request #545
Opened 2021-12-10 22:18 UTC by Sharpe49

https://bugs.launchpad.net/or/+bug/1954541

Please tell me in this pull request if you see textures not being rendered because that means that they are not yet marked in their renderer.

2021-12-13 12:24 UTC, twpol requested changes
I'd like to request not merging this until I've had a chance to review the forum thread and confirmed why we need this change (please keep all discussion there). In particular, whether we need to include it in a new 1.4 release.

2021-12-13 12:25 UTC, twpol commented
> I'd like to request not merging this until I've had a chance to review the forum thread and confirmed why we need this change (please keep all discussion there). In particular, whether we need to include it in a new 1.4 release.

Oh, I did not see this is still a draft - that's useful, so thanks for that!

2022-02-08 03:03 UTC, Sharpe49 commented
As proposed on the forum, this pull request is no longer a draft.

2022-02-09 19:26 UTC, twpol approved these changes

2022-02-09 19:27 UTC, merged