02k: Removed menu option Override non-electrified route line-voltage
openrails/openrails pull request #598
Opened 2022-02-12 14:18 UTC by cjakeman

See https://blueprints.launchpad.net/or/+spec/update-menu-options
and http://www.elvastower.com/forums/index.php?/topic/35301-menu-options/

Can now run electric locos on non-electricified routes.
An information message is shown when the pantograph is raised.

2022-02-13 03:35 UTC, Sharpe49 requested changes

2022-02-13 03:35 UTC, Sharpe49 commented on Source/ORTS.Settings/UserSettings.cs
> +        //public bool OverrideNonElectrifiedRoutes { get; set; }
```suggestion
```

2022-02-13 09:18 UTC, cjakeman commented on Source/ORTS.Settings/UserSettings.cs
> +        //public bool OverrideNonElectrifiedRoutes { get; set; }
Thanks, Cedric. Missed that.

2022-02-13 19:10 UTC, pzgulyas submitted a review, later dismissed
Seems good

2022-03-04 15:25 UTC, Sharpe49 approved these changes

2022-03-04 15:30 UTC, Sharpe49 requested changes
The merge was incomplete. You probably should rebase your branches instead of merging.

2022-03-06 15:47 UTC, cjakeman commented
@Sharpe49 Hi Cedric,

Thanks for that.

I've overcome the conflicts, now, so it would be great if you could re-approve this PR.

Thanks,

Chris

2022-03-06 23:10 UTC, Sharpe49 approved these changes

2022-03-07 08:22 UTC, merged