Container loaded wagons in Multiplayer mode
openrails/openrails pull request #695
Opened 2022-08-17 16:42 UTC by Csantucci

https://blueprints.launchpad.net/or/+spec/mp-containers

2022-08-17 23:31 UTC, Sharpe49 requested changes

2022-08-18 14:30 UTC, Csantucci commented
Removed all redundant wagon call parameters

2022-08-20 13:14 UTC, Sharpe49 approved these changes
Seems good now.

2022-08-20 15:06 UTC, Csantucci commented
> Seems good now.

Thank you. Now awaiting the approval of the blueprint to merge.

2022-08-21 18:38 UTC, merged