battery switch two buttons option in combination with a delay
openrails/openrails pull request #822
Opened 2023-04-23 14:03 UTC by sweiland-openrails

When using the battery switch two buttons option in combination with a delay:

Engine (
    ORTSBattery (
    Mode ( PushButtons )
    Delay ( 2s )
    DefaultOn ( 1 )
)

battery does not get switched on/off.

2023-04-24 07:51 UTC, cesarBLG requested changes
I don't think this is 100% correct. This will cause the physical button on the cab to return to 0 while being pressed, as well as triggering the sound before the button has been released. I'm analyzing the original code and I don't see any obvious issue, so it might be related to your CVF. I'll try to test it.

Okay, so I tested and it works correctly on my side, so I think this is not an OpenRails bug, but something in your CVF (probably you are using Style ( ONOFF ) instead of Style ( PRESSED ))

2023-04-24 18:25 UTC, sweiland-openrails commented
> I don't think this is 100% correct. This will cause the physical button on the cab to return to 0 while being pressed, as well as triggering the sound before the button has been released. I'm analyzing the original code and I don't see any obvious issue, so it might be related to your CVF. I'll try to test it.
> 
> Okay, so I tested and it works correctly on my side, so I think this is not an OpenRails bug, but something in your CVF (probably you are using Style ( ONOFF ) instead of Style ( PRESSED ))

Ok, I'll give it another look. I'm rather new to Open Rails, where does the abbreviation CVF stand for?

2023-04-24 18:58 UTC, cesarBLG commented
Don't worry. CVF is the CabView File, which is usually located inside the CabView folder of a locomotive. The syntax of CVF files allows several types of buttons: Style ( ONOFF ) means that when you push a button it'll remain active until you push it again, while Style ( PRESSED ) means that it goes back to the original position when you release it.

I tested the bug by adding the block you suggest:
```
Engine (
ORTSBattery (
Mode ( PushButtons )
Delay ( 2s )
DefaultOn ( 1 )
)
```
And added the following to the .cvf file of the locomotive:
```
TwoState (
	Type ( ORTS_BATTERY_SWITCH_COMMAND_BUTTON_CLOSE TWO_STATE )
	Position ( 100 420 24 12 )
	Graphic ( "battery_on.ace" )
	NumFrames ( 2 2 1 )
	Style ( PRESSED )
	MouseControl ( 1 )
)
TwoState (
	Type ( ORTS_BATTERY_SWITCH_COMMAND_BUTTON_OPEN TWO_STATE )
	Position ( 115 420 24 12 )
	Graphic ( "battery_off.ace" )
	NumFrames ( 2 2 1 )
	Style ( PRESSED )
	MouseControl ( 1 )
)
```
And I'm getting the correct behaviour, so I couldn't reproduce the bug.
It works for me also using the keyboard (Insert for closing, Ctrl+Insert for opening).

2023-05-02 18:47 UTC, sweiland-openrails commented
Bought a secondhand SDD, so some more diskspace to experiment.

Still I see the same problem. I have no battery statements in my .cvf file. I'm testing with the keys <Insert> and <Ctrl+Insert>. Works correctly without the delay or a delay of 0 seconds. But with a delay the Battery switch in the Train Driving Info (F5) does not move. I'll have another look in the code...

Thanks for explaining me about the .cvf file.

2023-05-02 19:29 UTC, cesarBLG commented
Ah, I now see your thinking. The original code requires you to keep the button pressed _until_ the battery is connected, so you have to keep <Ctrl+Insert> pressed for two seconds. This is the correct behaviour for other electrical switches as the circuit breaker, but I don't know about the battery.

You could post a question at Elvas Tower to see if the button has to kept pushed until switch is closed in real trains.

2023-05-03 07:02 UTC, sweiland-openrails commented
Ah, thanks. I thought I tested keeping the button pressed. Tested once again and it works as you describe, keeping the button pressed. Seems logical to me, pressing the button for two seconds. Can I Undo this Pull Request by pressing the "Close with comment" button?

2023-05-03 14:40 UTC, cesarBLG submitted a review, later dismissed
Yeah, I think adding it to the documentation is a good idea.

2023-05-04 14:11 UTC, sweiland-openrails commented
If I now merge this change I not only have a changed .rst documentation file, but also the  BatterySwitch.cs file. That's because this .cs file contains 3 extra bytes EF BB BF (which is some UTF-8 byte order mark). I don't want to pollute the history of this BatterySwitch.cs with an extra non existent change. Any idea how I can get rid of this change? Git does not see this as a change, so I cannot commit the file without 3 extra bytes.
Or can I just close the Pull Request without the merge and redo the fix only in the .rst file?

2023-05-05 09:46 UTC, cesarBLG commented
I fixed it with a simple trick

2023-05-05 09:46 UTC, cesarBLG approved these changes

2023-05-05 09:52 UTC, merged

2023-05-05 17:31 UTC, sweiland-openrails commented
thanks...